convert yaml references to commands, available in 2.1 config format

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,85 +16,143 @@
 #
 # Check https://circleci.com/docs/2.0/language-python/ for more details
 #
-version: 2
+version: 2.1
 
-install_git_lfs: &install_git_lfs
-  run:
-    name: Install git LFS
-    command: |
-      # circleci images don't currently come with git lfs installed:
-      #   https://support.circleci.com/hc/en-us/articles/360044671191-git-lfs-support-on-CircleCI-provided-images
-      # Install it manually, as suggested.
-      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
-      sudo apt-get install git-lfs
-      git lfs install
+commands:
 
-lfs_caching:
-  save_ids: &save_lfs_ids
-    run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
-  restore_cache: &restore_lfs_cache
-    restore_cache:
-      keys:
+  install_git_lfs:
+    steps:
+    - run:
+        name: Install git LFS
+        command: |
+          # circleci images don't currently come with git lfs installed:
+          #   https://support.circleci.com/hc/en-us/articles/360044671191-git-lfs-support-on-CircleCI-provided-images
+          # Install it manually, as suggested.
+          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
+          sudo apt-get install git-lfs
+          git lfs install
+
+  git_lfs_caching:
+    # this command needs this environment variable: GIT_LFS_SKIP_SMUDGE: 1
+    steps:
+    - run:
+        name: Save unique Git LFS identifiers to a file
+        command: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+    - restore_cache:
+        keys:
         - v1-lfscache-{{ checksum ".lfs-assets-id" }}
         - v1-lfscache-
-  lfs_pull: &lfs_pull
-    run: git lfs pull
-  save_cache: &save_lfs_cache
-    save_cache:
-      paths:
-        - .git/lfs
-      key: v1-lfscache-{{ checksum ".lfs-assets-id" }}
+    - run:
+        name: Git LFS pull anything not restored from cache
+        command: git lfs pull
+    - save_cache:
+        paths:
+          - .git/lfs
+        key: v1-lfscache-{{ checksum ".lfs-assets-id" }}
 
-check_services_status: &check_services_status
-  command: |
-    set -x
+  check_services_status:
+    parameters:
+      working_directory:
+        description: working directory
+        type: string
+        default: ~/project/.circleci
+      step_name:
+        description: step name
+        type: string
+        default: Check AS services status
+    steps:
+      - run:
+          name: << parameters.step_name >>
+          working_directory: << parameters.working_directory >>
+          command: |
+            set -x
 
-    sleep 10  # Give the services enough time to start (or fail)
+            sleep 10  # Give the services enough time to start (or fail)
 
-    for c in as1301 as1303 as1305; do
-      docker-compose exec $c /bin/bash -c \
-        '! systemctl is-failed scion-* || (systemctl status scion-* --no-pager --full && false)'
-    done
+            for c in as1301 as1303 as1305; do
+              docker-compose exec $c /bin/bash -c \
+                '! systemctl is-failed scion-* || (systemctl status scion-* --no-pager --full && false)'
+            done
 
-check_scion_connections: &check_scion_connections
-  command: |
-    set -x
+  check_scion_connections:
+    parameters:
+      working_directory:
+        description: working directory
+        type: string
+        default: ~/project/.circleci
+      step_name:
+        description: step name
+        type: string
+        default: Check SCION connections
+    steps:
+      - run:
+          name: << parameters.step_name >>
+          no_output_time: "3m0s"
+          working_directory: << parameters.working_directory >>
+          command: |
+            set -x
 
-    # Wait for 3 beacons received from now on
-    docker-compose exec -T as1303 /bin/bash -c \
-      "while curl -s 127.0.0.1:30454/metrics | egrep -q 'control_beaconing_received_beacons_total{.*}.[0]+'; do sleep 1; done"
-    docker-compose exec -T as1305 /bin/bash -c \
-      "while curl -s 127.0.0.1:30454/metrics | egrep -q 'control_beaconing_received_beacons_total{.*}.[0]+'; do sleep 1; done"
+            # Wait for 3 beacons received from now on
+            docker-compose exec -T as1303 /bin/bash -c \
+              "while curl -s 127.0.0.1:30454/metrics | egrep -q 'control_beaconing_received_beacons_total{.*}.[0]+'; do sleep 1; done"
+            docker-compose exec -T as1305 /bin/bash -c \
+              "while curl -s 127.0.0.1:30454/metrics | egrep -q 'control_beaconing_received_beacons_total{.*}.[0]+'; do sleep 1; done"
 
-    # Show paths used by SCMP
-    docker-compose exec --user user -T as1301 scion showpaths 19-ffaa:0:1303
-    docker-compose exec --user user -T as1303 scion showpaths 19-ffaa:0:1301
-    docker-compose exec --user user -T as1305 scion showpaths 19-ffaa:0:1301
+            # Show paths used by SCMP
+            docker-compose exec --user user -T as1301 scion showpaths 19-ffaa:0:1303
+            docker-compose exec --user user -T as1303 scion showpaths 19-ffaa:0:1301
+            docker-compose exec --user user -T as1305 scion showpaths 19-ffaa:0:1301
 
-    # Check that we can SCMP
-    docker-compose exec --user user -T as1301 scion ping -c 5 19-ffaa:0:1303,127.0.0.1
-    docker-compose exec --user user -T as1303 scion ping -c 5 19-ffaa:0:1301,127.0.0.1
-    docker-compose exec --user user -T as1305 scion ping -c 5 19-ffaa:0:1301,127.0.0.1
+            # Check that we can SCMP
+            docker-compose exec --user user -T as1301 scion ping -c 5 19-ffaa:0:1303,127.0.0.1
+            docker-compose exec --user user -T as1303 scion ping -c 5 19-ffaa:0:1301,127.0.0.1
+            docker-compose exec --user user -T as1305 scion ping -c 5 19-ffaa:0:1301,127.0.0.1
 
-start_coordinator: &start_coordinator
-  command: |
-    # Initialize coordinator with test data and test keys
-    docker-compose run -T coord /bin/bash -c \
-     './scripts/init-test-db.sh && \
-      cp .circleci/setup/deploy_ssh_config run/ssh_config && \
-      cp .circleci/setup/deploy_rsa* run/ && \
-      chmod 644 run/deploy_rsa.pub && \
-      chmod 600 run/deploy_rsa'
+  start_coordinator:
+    parameters:
+      working_directory:
+        description: working directory
+        type: string
+        default: ~/project/.circleci
+      step_name:
+        description: step name
+        type: string
+        default: Start coordinator container
+    steps:
+      - run:
+          name: << parameters.step_name >>
+          working_directory: << parameters.working_directory >>
+          command: |
+            # Initialize coordinator with test data and test keys
+            docker-compose run -T coord /bin/bash -c \
+             './scripts/init-test-db.sh && \
+              cp .circleci/setup/deploy_ssh_config run/ssh_config && \
+              cp .circleci/setup/deploy_rsa* run/ && \
+              chmod 644 run/deploy_rsa.pub && \
+              chmod 600 run/deploy_rsa'
 
-    docker-compose up -d coord
+            docker-compose up -d coord
 
-check_coordinator_ready: &check_coordinator_ready
-  command: |
-    # We start another container in the same network as `coord` to check `coord` is ready.
-    # All exposed ports from `coord` are available on `localhost` in this new container.
-    # NOTE: uses python:3.6 to re-use already fetched image from `coord`; contains more tools than ubuntu:xenial
-    docker run --net circleci_as_net --entrypoint /bin/bash python:3.6 -c \
-      'wget --tries 10 --retry-connrefused http://coord:8000/login/'
+  check_coordinator_ready:
+    parameters:
+      working_directory:
+        description: working directory
+        type: string
+        default: ~/project/.circleci
+      step_name:
+        description: step name
+        type: string
+        default: Coordinator health check
+    steps:
+      - run:
+          name: << parameters.step_name >>
+          working_directory: << parameters.working_directory >>
+          command: |
+            # We start another container in the same network as `coord` to check `coord` is ready.
+            # All exposed ports from `coord` are available on `localhost` in this new container.
+            # NOTE: uses python:3.6 to re-use already fetched image from `coord`; contains more tools than ubuntu:xenial
+            docker run --net circleci_as_net --entrypoint /bin/bash python:3.6 -c \
+              'wget --tries 10 --retry-connrefused http://coord:8000/login/'
 
 jobs:
   basic:
@@ -105,15 +163,11 @@ jobs:
       GIT_LFS_SKIP_SMUDGE: 1
 
     steps:
-      - <<: *install_git_lfs
+      - install_git_lfs
 
       - checkout
 
-      # Handle caching of files stored using Git LFS
-      - <<: *save_lfs_ids
-      - <<: *restore_lfs_cache
-      - <<: *lfs_pull
-      - <<: *save_lfs_cache
+      - git_lfs_caching
 
       # Download and cache dependencies
       - restore_cache:
@@ -165,15 +219,11 @@ jobs:
     environment:
       GIT_LFS_SKIP_SMUDGE: 1
     steps:
-      - <<: *install_git_lfs
+      - install_git_lfs
 
       - checkout
 
-      # Handle caching of files stored using Git LFS
-      - <<: *save_lfs_ids
-      - <<: *restore_lfs_cache
-      - <<: *lfs_pull
-      - <<: *save_lfs_cache
+      - git_lfs_caching
 
       - run:
           name: Extract host configuration info from testdata.yaml fixture
@@ -189,15 +239,9 @@ jobs:
             docker build --file ~/project/deploy/Dockerfile-django --tag scionlab_django ~/project/ # Build base image, as used in production
             docker-compose build
 
-      - run:
-          name: Start coordinator
-          working_directory: ~/project/.circleci
-          <<: *start_coordinator
+      - start_coordinator
 
-      - run:
-          name: Check coordinator ready
-          working_directory: ~/project/.circleci
-          <<: *check_coordinator_ready
+      - check_coordinator_ready
 
       # Start integration tests
       - run:
@@ -214,16 +258,9 @@ jobs:
 
             docker-compose logs
 
-      - run:
-          name: Check AS services status
-          working_directory: ~/project/.circleci
-          <<: *check_services_status
+      - check_services_status
 
-      - run:
-          name: Check SCION connections
-          working_directory: ~/project/.circleci
-          no_output_time: "3m0s"
-          <<: *check_scion_connections
+      - check_scion_connections
 
       - run:
           name: "Push changes to AS ffaa:0:1303"
@@ -314,7 +351,7 @@ jobs:
       image: ubuntu-1604:201903-01
 
     steps:
-      - <<: *install_git_lfs
+      - install_git_lfs
 
       # Start old version of coordinator
       - run:
@@ -339,15 +376,13 @@ jobs:
             docker-compose build
 
 
-      - run:
-          name: OLD -- Start coordinator
+      - start_coordinator:
+          step_name: OLD -- Start coordinator
           working_directory: ~/previous_version/.circleci
-          <<: *start_coordinator
 
-      - run:
-          name: OLD -- Check coordinator ready
+      - check_coordinator_ready:
+          step_name: OLD -- Check coordinator ready
           working_directory: ~/previous_version/.circleci
-          <<: *check_coordinator_ready
 
       - run:
           name: OLD -- Start ASes
@@ -364,10 +399,9 @@ jobs:
 
             docker-compose logs
 
-      - run:
-          name: OLD -- Check AS services status
+      - check_services_status:
+          step_name: OLD -- Check AS services status
           working_directory: ~/previous_version/.circleci
-          <<: *check_services_status
 
       - run:
           name: OLD -- Start VPN containers and verify the connection over VPN works
@@ -408,10 +442,9 @@ jobs:
             cp -r ~/previous_version/run ~/project/
             docker-compose up -d --force-recreate --build coord huey
 
-      - run:
-          name: NEW -- Check coordinator ready
+      - check_coordinator_ready:
+          step_name: NEW -- Check coordinator ready
           working_directory: ~/project/.circleci
-          <<: *check_coordinator_ready
 
       - run:
           name: OLD -- Run client cronjob
@@ -429,16 +462,13 @@ jobs:
                  sudo mv /.dockerenv.bk /.dockerenv;'
             done
 
-      - run:
-          name: NEW -- Check updated AS services status
+      - check_services_status:
+          step_name: NEW -- Check updated AS services status
           working_directory: ~/project/.circleci
-          <<: *check_services_status
 
-      - run:
-          name: NEW -- Check SCION connections
+      - check_scion_connections:
+          step_name: NEW -- Check SCION connections
           working_directory: ~/project/.circleci
-          no_output_time: "3m0s"
-          <<: *check_scion_connections
 
       - run:
           name: NEW -- Check updated configuration matches VPN setup
