Scionlab version upgrade integration test with packages (#242)
* Add upgrade integration test

* Use django entrypoint in coordinator, test migration

* Use new packages-test test repository

* Check for fresh beacons in logs

* Show all paths used in connectivity test

* Show failed unit

* Use the same scionlab prerm in docker

* Check updated coordinator is up and running before package upgrade

* TODO: remove /var/lib/scion purge, should be handled by the installation itself

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,6 +17,64 @@
 # Check https://circleci.com/docs/2.0/language-python/ for more details
 #
 version: 2
+
+check_services_status: &check_services_status
+  command: |
+    set -x
+
+    sleep 10  # Give the services enough time to start (or fail)
+
+    for c in as1301 as1303 as1305; do
+      docker-compose exec $c /bin/bash -c \
+        '! systemctl is-failed scion-* || (systemctl status scion-* --no-pager --full && false)'
+    done
+
+check_scion_connections: &check_scion_connections
+  command: |
+    set -x
+
+    # Wait for 3 beacons received from now on
+    docker-compose exec -T as1303 /bin/bash -c \
+      "tail -n 0 -f /var/log/scion/* | awk '/Registered beacons/ {c++; if(c>=3) exit(0)}'"
+    docker-compose exec -T as1305 /bin/bash -c \
+      "tail -n 0 -f /var/log/scion/* | awk '/Registered beacons/ {c++; if(c>=3) exit(0)}'"
+
+    # Show paths used by SCMP
+    docker-compose exec -T as1301 /bin/bash -c \
+      'showpaths -srcIA 19-ffaa:0:1301 -dstIA 19-ffaa:0:1303 || true'
+    docker-compose exec -T as1303 /bin/bash -c \
+      'showpaths -srcIA 19-ffaa:0:1303 -dstIA 19-ffaa:0:1301 || true'
+    docker-compose exec -T as1305 /bin/bash -c \
+      'showpaths -srcIA 19-ffaa:0:1305 -dstIA 19-ffaa:0:1301 || true'
+
+    # Check that we can SCMP
+    docker-compose exec -T as1301 /bin/bash -c \
+      'scmp echo -c 5 -local 19-ffaa:0:1301,[127.0.0.1] -remote 19-ffaa:0:1303,[127.0.0.1]'
+    docker-compose exec -T as1303 /bin/bash -c \
+      'scmp echo -c 5 -local 19-ffaa:0:1303,[127.0.0.1] -remote 19-ffaa:0:1301,[127.0.0.1]'
+    docker-compose exec -T as1305 /bin/bash -c \
+      'scmp echo -c 5 -local 19-ffaa:0:1305,[127.0.0.1] -remote 19-ffaa:0:1301,[127.0.0.1]'
+
+start_coordinator: &start_coordinator
+  command: |
+    # Initialize coordinator with test data and test keys
+    docker-compose run -T coord /bin/bash -c \
+     './scripts/init-test-db.sh && \
+      cp .circleci/setup/deploy_ssh_config run/ssh_config && \
+      cp .circleci/setup/deploy_rsa* run/ && \
+      chmod 644 run/deploy_rsa.pub && \
+      chmod 600 run/deploy_rsa'
+
+    docker-compose up -d coord
+
+check_coordinator_ready: &check_coordinator_ready
+  command: |
+    # We start another container in the same network as `coord` to check `coord` is ready.
+    # All exposed ports from `coord` are available on `localhost` in this new container.
+    # NOTE: uses python:3.6 to re-use already fetched image from `coord`; contains more tools than ubuntu:xenial
+    docker run --net circleci_as_net --entrypoint /bin/bash python:3.6 -c \
+      'wget --tries 10 --retry-connrefused http://coord:8000/login/'
+
 jobs:
   basic:
     docker:
@@ -88,26 +146,18 @@ jobs:
           working_directory: ~/project/.circleci
           command: |
             sed -i '/.circleci/d' ~/project/.dockerignore  # The .dockerignore is for production, we'll need this
+            docker build --file ~/project/deploy/Dockerfile-django --tag scionlab_django ~/project/ # Build base image, as used in production
             docker-compose build
 
       - run:
           name: Start coordinator
           working_directory: ~/project/.circleci
-          command: |
-            docker-compose run -T coord /bin/bash -c \
-             './scripts/init-test-db.sh && \
-              cp .circleci/setup/deploy_ssh_config run/ssh_config && \
-              cp .circleci/setup/deploy_rsa* run/ && \
-              chmod 644 run/deploy_rsa.pub && \
-              chmod 600 run/deploy_rsa'
+          <<: *start_coordinator
 
-            docker-compose up -d coord
-
-            # We start another container in the same network as `coord` to check `coord` is ready.
-            # All exposed ports from `coord` are available on `localhost` in this new container.
-            # NOTE: uses python:3.6 to re-use already fetched image from `coord`; contains more tools than ubuntu:xenial
-            docker run --net circleci_as_net --entrypoint /bin/bash python:3.6 -c \
-              'wget --tries 10 --retry-connrefused http://coord:8000/login/'
+      - run:
+          name: Check coordinator ready
+          working_directory: ~/project/.circleci
+          <<: *check_coordinator_ready
 
       # Start integration tests
       - run:
@@ -127,36 +177,13 @@ jobs:
       - run:
           name: Check AS services status
           working_directory: ~/project/.circleci
-          command: |
-            set -x
-
-            sleep 10  # Give the services enough time to start (or fail)
-
-            for c in as1301 as1303 as1305; do
-              docker-compose exec $c /bin/bash -c \
-                '! systemctl is-failed scion-*'
-            done
+          <<: *check_services_status
 
       - run:
           name: Check SCION connections
           working_directory: ~/project/.circleci
           no_output_time: "3m0s"
-          command: |
-            set -x
-
-            # Wait for beacons
-            docker-compose exec -T as1303 /bin/bash -c \
-              'until [ `grep "Registered beacons" -s -r /var/log/scion/ | wc -l` -ge 5 ]; do sleep 0.1; done;'
-            docker-compose exec -T as1305 /bin/bash -c \
-              'until [ `grep "Registered beacons" -s -r /var/log/scion/ | wc -l` -ge 5 ]; do sleep 0.1; done;'
-
-            # Check that we can SCMP
-            docker-compose exec -T as1301 /bin/bash -c \
-              'scmp echo -c 5 -local 19-ffaa:0:1301,[127.0.0.1] -remote 19-ffaa:0:1303,[127.0.0.1]'
-            docker-compose exec -T as1303 /bin/bash -c \
-              'scmp echo -c 5 -local 19-ffaa:0:1303,[127.0.0.1] -remote 19-ffaa:0:1301,[127.0.0.1]'
-            docker-compose exec -T as1305 /bin/bash -c \
-              'scmp echo -c 5 -local 19-ffaa:0:1305,[127.0.0.1] -remote 19-ffaa:0:1301,[127.0.0.1]'
+          <<: *check_scion_connections
 
       - run:
           name: "Push changes to AS ffaa:0:1303"
@@ -246,9 +273,118 @@ jobs:
              'until [ `grep "Registered beacons" -s -r /var/log/scion/ | wc -l` -ge 5 ]; do sleep 0.1; done; \
               scmp echo -c 10 -local 20-ffaa:1:4,[127.0.0.1] -remote 20-ffaa:0:1405,[127.0.0.1]'
 
+  upgrade_integration:
+    machine:
+      image: ubuntu-1604:201903-01
+
+    steps:
+      # Start old version of coordinator
+      - run:
+          name: OLD -- Checkout
+          working_directory: ~/
+          command: |
+            git clone https://github.com/netsec-ethz/scionlab.git -b master ~/previous_version
+
+      - run:
+          name: OLD -- Extract host configuration info from testdata.yaml fixture
+          working_directory: ~/previous_version
+          command: |
+            pip install pyyaml
+            python .circleci/setup/generate-host-envs.py
+
+      - run:
+          name: OLD -- Build container images
+          working_directory: ~/previous_version/.circleci
+          command: |
+            #docker build --file ~/project/previous_version/deploy/Dockerfile-django --tag scionlab_django ~/project/ # We are only extending the production image
+            sed -i '/.circleci/d' ~/previous_version/.dockerignore  # The .dockerignore is for production, we'll need this
+            docker-compose build
+
+
+      - run:
+          name: OLD -- Start coordinator
+          working_directory: ~/previous_version/.circleci
+          <<: *start_coordinator
+
+      - run:
+          name: OLD -- Check coordinator ready
+          working_directory: ~/previous_version/.circleci
+          <<: *check_coordinator_ready
+
+      - run:
+          name: OLD -- Start ASes
+          working_directory: ~/previous_version/.circleci
+          command: |
+            set -x
+            docker-compose up -d as1301 as1303 as1305
+
+            for c in as1301 as1303 as1305; do
+              docker-compose exec $c /bin/bash -c \
+                'apt-get install --assume-yes scionlab; \
+                 scionlab-config --host-id ${SCIONLAB_HOST_ID} --host-secret ${SCIONLAB_HOST_SECRET} --url http://coord:8000'
+            done
+
+            docker-compose logs
+
+      - run:
+          name: OLD -- Check AS services status
+          working_directory: ~/previous_version/.circleci
+          <<: *check_services_status
+
+      # Starting upgrade integration tests
+
+      - checkout
+
+      - run:
+          name: NEW -- Rebuild and start coordinator from current branch
+          working_directory: ~/project/.circleci
+          command: |
+            sed -i '/.circleci/d' ~/project/.dockerignore  # The .dockerignore is for production, we'll need this
+            docker build --file ~/project/deploy/Dockerfile-django --tag scionlab_django ~/project/
+            sudo chown circleci:circleci -R ~/previous_version/run/
+            cp -r ~/previous_version/run ~/project/
+            docker-compose up -d --force-recreate --build coord huey
+
+      - run:
+          name: NEW -- Check coordinator ready
+          working_directory: ~/project/.circleci
+          <<: *check_coordinator_ready
+
+      - run:
+          name: OLD -- Run client cronjob
+          working_directory: ~/previous_version/.circleci
+          command: |
+            set -x
+            # Simulate command that is executed on hosts with upgrade cronjob (VMs), upgrade package
+            for c in as1301 as1303 as1305; do
+              # We have to hide the /.dockerenv file, since the scionlab packages assume that they cannot use systemd, run systemctl when run in docker
+              # TODO: remove purging db file, rm /var/lib/scion/*, needs to be done as part of the upgrade itself
+              docker-compose exec -T $c /bin/bash -c \
+                'echo "deb [trusted=yes] https://packages-test.netsec.inf.ethz.ch/debian all main" | sudo tee /etc/apt/sources.list.d/scionlab.list; \
+                 apt-get update; \
+                 rm /var/lib/scion/*; sudo mv /.dockerenv /.dockerenv.bk; \
+                 DEBIAN_FRONTEND=noninteractive apt-get install -y --only-upgrade scionlab; \
+                 sudo mv /.dockerenv.bk /.dockerenv; '
+            done
+
+      - run:
+          name: NEW -- Check updated AS services status
+          working_directory: ~/project/.circleci
+          <<: *check_services_status
+
+      - run:
+          name: NEW -- Check SCION connections
+          working_directory: ~/project/.circleci
+          no_output_time: "3m0s"
+          <<: *check_scion_connections
+
 workflows:
   version: 2
   tests:
     jobs:
       - basic
       - integration
+      - upgrade_integration:
+          filters:
+            branches:
+              only: /.*_upgrade_.*/
